### ISSUE TITLE
Remove the sample

### ISSUE THREAD

**Issue by akhilthomas011** [azureautomation/auto-resize-azure-vms-by-using-tags#2]
I have added the sample in my personal repository with proper topic and it got reflected in Runbook Gallery. Please go ahead and remove this sample from here, as it creates duplicate.

@AutomationProductTeam @Jinesh12 

This is the link to the new one: https://github.com/akhilthomas011/Auto-Resize-Azure-VM-with-Tags

**Comment by jineshcodes** [comment]
Sure. Will remove the TAG from the Github repo. This will make sure this repo/runbook is not visible in the Azure portal. 
Thanks for your contributions!
